import{a as b,S as v,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const w=async(r,s)=>{const o=new URLSearchParams({key:"44484405-088f061e287c84f80e0f16531",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15});return await b.get(`https://pixabay.com/api/?${o}`)},O=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),M=(r,s)=>{const o=r.map(({largeImageURL:a,webformatURL:e,tags:t,likes:n,views:g,comments:h,downloads:L})=>`<li name="galleryItem" class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img src="${e}" alt="${t}" />
        </a>
        <div class="description">
          <p>Likes <span class="desc-span">${n}</span></p>
          <p>Views <span class="desc-span">${g}</span></p>
          <p>Comments <span class="desc-span">${h}</span></p>
          <p>Downloads <span class="desc-span">${L}</span></p>
        </div>
      </li>`).join("");s.insertAdjacentHTML("beforeend",o),O.refresh()},c=document.querySelector("section").children,m=c.getForm,y=c.loader,p=c.gallery,i=c.loadMore;let d=1,u;l.settings({progressBar:!1,timeout:4e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight"});const f=async(r,s=1)=>{try{const a=await w(r,s);if(y.style.display="block",a.data.hits.length===0)return l.warning({message:"Sorry, there are no images matching your search query. Please try again!"});i.style.display="block";const e=Math.ceil(a.data.totalHits/15);s===e&&(i.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results."})),M(a.data.hits,p)}catch{}finally{m.reset(),y.style.display="none"}const o=p.children.galleryItem.getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"})},P=async r=>{r.preventDefault(),p.innerHTML="",i.style.display="none",u=r.target.searchTerm.value.trim().toLowerCase(),d=1,f(u)},$=async()=>{d+=1,f(u,d)};m.addEventListener("submit",P);i.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
